version: "3.9"

services:
  postgres-vector:
    image: pgvector/pgvector:pg16
    container_name: postgres-vector
    restart: unless-stopped
    environment:
      POSTGRES_DB: vector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
